version: '3.8'

services:
  genset-network-1:
    build: .
    container_name: datakom-network-1
    environment:
      - DATAKOM_HOST=192.168.100.100
      - DATAKOM_PORT=502
      - EXPORTER_PORT=8000
    ports:
      - "8000:8000"
    restart: unless-stopped